### PR TITLE
feat: add tests for ppp_line and ppp_res examples

### LINKED ISSUE #11: Add test cases for the current functionality.
What do you think about adding tests for the current functionality? 
If this repository will be adding more features, maybe it's better to include them because someone's PR can break something else. 
I can help you add these basic tests if you agree.

### PR DESCRIPTION
**Pull request by horw**
Add base tests for examples from README.md.
close #11

### CODE REVIEW

**Comment by horw** [comment]
@bugen, I have just added a few lines and record tests. Could you please take a look and leave your comments? My plan is to add all the examples from the README.md

**Comment by bugen** [comment]
@horw Cool! Very clear, versatile.
Is it better to merge at this point, or should I wait until additional test cases are added?

**Comment by horw** [comment]
> @horw Cool! Very clear, versatile. Is it better to merge at this point, or should I wait until additional test cases are added?
It's nice to hear that you like it. Just wait for the rest of the examples; I will complete them in few days.

**Comment by horw** [comment]
@bugen you can check for updates. I've already added most of the tests and have also included pre-commit and CI tests.

**Comment by bugen** [comment]
Thank you @horw . The test code is excellent. I also appreciate the information about pre-commit and ci.yml.

Could you please explain ci.yml? Am I correct in understanding that `ruff` only performs linting and it doesn't handle formatting? If there are some linting errors, does that mean push won't be allowed?

**Comment by horw** [comment]
This basic CI.yml configuration for linting and tests without formatting. Its main purpose is to ensure that when people create new pull requests for your project, you can quickly determine if they pass basic tests. Sometimes, making changes might unexpected break other parts of the project. You can set up more complete tests using GitHub Actions, btw those are separate from the current pull request's purpose.

Pre-commit is also very helpful for maintaining code quality, but it requires installation to enforce these rules. For the next PR you can add additional rules for contributing. 

For further reading on this topic: 
- https://github.com/astral-sh/ruff/blob/982ae6ff08b832de0b39e3fdc9781a468ae3d19c/README.md?plain=1#L148
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks
- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule
- https://stackoverflow.com/questions/65580689/how-we-can-disable-merge-of-a-pull-request-in-github-if-any-check-fails-in-the-c

**Comment by bugen** [comment]
@horw Thank you for the explanation. I have a general understanding of what you are trying to do. Maintaining code quality is important, so I agree with the content of this PR.  When I checked the current pypipe.py using `ruff`, I already found some errors...
Is it okay to merge this content for now, or are there still additional changes to be made to this PR?

**Comment by horw** [comment]
P.S. there are many other linters available such as flake 8, black, etc. And you can choose which you like.
Yes, you can merge the current content.

**Comment by bugen** [comment]
@horw I merged. Thank you for your contribution.

**Pull request merged**
