### PR TITLE
Added wasmer integration package

### PR DESCRIPTION
**Pull request by syrusakbary**
I've added integration as a [wasmer package](https://wasmer.io/) as it can be easier to demonstrate pypipe with it to newcomers.

Simply do
```
alias ppp="wasmer run syrusakbary/pypipe@0.1.0 -- "
```
(note: change this so bugen is the owner and not myself,  happy to transfer once you have an account in Wasmer!)

And then `cat staff.txt | ppp 'i, line.upper()'` (or similar)

Hope you like it!

### CODE REVIEW

**Comment by syrusakbary** [comment]
Also happy to add CI/CD integration so a new version is published per commit in master

**Comment by bugen** [comment]
I'm delighted that pypipe can be integrated with your great project. 
In addition to this pull request, there have been other issues related to pipx support #4, so I plan to organize the installation methods and update the README. Of course, I'll also include information about Wasmer.

> Also happy to add CI/CD integration so a new version is published per commit in master (just let me know if interested)

What kind of action is required? If maintenance isn't too burdensome, I'm open to considering it positively.

**Comment by diazona** [comment]
I was actually planning to include CI/CD integration as part of my PR for #4, because the package needs to be published to PyPI to support installation with pipx. (well not really, but in some sort of practical sense it should be) Should I hold off on that?

**Comment by bugen** [comment]
> I was actually planning to include CI/CD integration as part of my PR for #4, because the package needs to be published to PyPI to support installation with pipx. (well not really, but in some sort of practical sense it should be) Should I hold off on that?

Sorry to trouble you... pypipe is my first venture into OSS development, so there are many things I'm not familiar with. I've released it with the hope that everyone will find it useful, and I believe expanding the ways to adopt pypipe is important, and I'm willing to put in the effort for that. I'm just a bit worried because of my lack of experience, and the term 'burdensome' might not have been the best choice of words (I'm not a native English speaker, so my expressions can sometimes be off). I think CI/CD would actually help reduce the workload, so please do teach me about that process. Working on PyPI is not a problem for me.

**Comment by bugen** [comment]
@syrusakbary Thank you! I merged.

**Pull request merged**
